### ISSUE TITLE
Dino Run fails to run

### ISSUE THREAD

**Issue by parkerlreed** [HarryPeach/DinoRunNX#4]
Worked yesterday. Greeted by this today

![IMG_20190505_192252](https://user-images.githubusercontent.com/841440/57201872-a9f3f780-6f6c-11e9-969d-9d0726c5dca3.jpg)

**Comment by HarryPeach** [comment]
Could you verify that the following folder structure exists on the switch?

`/atmosphere/hbl_html/html-document/.htdocs/dino_run`

If it does, what are the contents of it?

**Comment by parkerlreed** [comment]
assets, index.css, index.html, index.js

**Comment by parkerlreed** [comment]
And I just tried again and it loaded O.o. Nothing changed.

**Comment by HarryPeach** [comment]
Very weird, feel free to contact me if it happens again.

Closing this issue for now

**Comment by iEldik3** [comment]
I have the same problem,but it didn't fixed.

**Comment by HarryPeach** [comment]
> I have the same problem,but it didn't fixed.

Could I ask you to do the same as well? As well as what Switch firmware and CFW you're running?

> Could you verify that the following folder structure exists on the switch?
/atmosphere/hbl_html/html-document/.htdocs/dino_run
If it does, what are the contents of it?

**Comment by iEldik3** [comment]
index.css,index.html,index.js,folder assets that contains folder named "default_200_percent",with three png files:200-disabled.png,200-error-offline.png,200-offline-sprite.png.Firmware ver. 7.0.1,CFW-Atmosphere 0.8.9

**Comment by HarryPeach** [comment]
Does reinstalling the app fix the issue?

**Comment by iEldik3** [comment]
No
