### ISSUE TITLE
Dino Run crashes Atmosphère when B button is pressed

### ISSUE THREAD

**Issue by SMUS16475** [HarryPeach/DinoRunNX#5]
For Atmosphère version 0.10.2 and beyond, it seems that the Dino Run app tends to crash the entire firmware every time the B button is pressed instead of just going back to the hbmenu like it usually does. It's only an issue for those who access the hbmenu via title-override since you can't even run Dino Run on Applet Mode. Will there ever be a fix for this or will there be an updated version of Dino Run coming out soon?

**Comment by HarryPeach** [comment]
Could not recreate this, please try the latest version and see if the issue still occurs

**Comment by EmmanuelChiobi** [comment]
There's a newfound issue. Regarding the newest version of DinoRunNX, the game freezes on this screen upon launching:
![image](https://user-images.githubusercontent.com/90267631/163442041-dc0f1b53-7b02-42a1-ba8d-607509dfedac.png)

**Comment by HarryPeach** [comment]
Thanks for reporting @EmmanuelChiobi, would you mind creating a new issue for this? Thanks!
